name: testplugin
version: '1.0-SNAPSHOT'
main: com.brodi.test.Main
api-version: '1.20'
authors: [1lent]
description: Cool test plugin
commands:
  heal:
  craft:
  eat:
  fly:
  anvil:
  echest:
  grindstone: